**NumPy** stands for **Numerical Python** or **Numeric Python**. NumPy is the core Python library for scientific computing. Most computational packages providing scientific functionality use NumPy’s array objects.


NumPy is designed for efficiently handling large arrays of data.

NumPy operations perform complex computations on entire arrays without the need for Python for loops.

NumPy’s arrays are homogeneous structures.

Some important terms that will help us to work with NumPy arrays:
- NumPy `dimensions` are called `axes`. 
- The number of dimensions is the `rank` of the array. You can say that the number of axes defines the rank of the array.
- The `shape` of an array is a tuple of integers showing the size of the array along each dimension. 

**How to Create NumPy Arrays**

NumPy arrays can be created:
- From other Python structures, for example lists or tuples using an `array()` function
- Using `random` functions to create an array of random data, or using the `range()` function to create an array of a sequence of numbers
- Using one of the `zeros()`, `ones()` or `empty()` functions to create arrays of `0`s or `1`s or an array of uninitialized empty elements

**Examples**

In [1]:
import numpy as np #we need to import numpy library to use numpy functionalities.

In [2]:
#The most obvious examples of array-like structures are lists and tuples.

In [3]:
# First, use a simple list of 4 integer numbers to create an array

list_int = [10, 30, 34, 111]
a_int = np.array(list_int)
a_int

array([ 10,  30,  34, 111])

To check the rank of the array, use `ndim`.

In [4]:
a_int.ndim

1

The output of `.shape` is a tuple of integers indicating the size of the array in each dimension. For a 1-dimensional array, this represents the number of elements along a single axis.  

In [5]:
a_int.shape

(4,)

The type of the object can be checked with `type()` function.

In [6]:
type(a_int)

numpy.ndarray

`dtype` returns an object describing the type of the elements in the array.

In [7]:
a_int.dtype

dtype('int64')

To create a 2-dimensional array, we can use a list of lists.

In [8]:
list_2dim = [[1.5,2,3], [4,5,6]] #creates 2 rows 3 columns array. 
a_2dim = np.array(list_2dim)
a_2dim

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [9]:
print(a_2dim.ndim)  # number of dimensions
print(a_2dim.shape) # the size of the array in each dimension

2
(2, 3)


For a matrix with `n` rows and `m` columns the shape will be `(n,m)`.

In [10]:
#Create a 1-dimensional array from a list and find type of the array. 
import numpy as np
list_new=[2, 5.5, 3.1415, 0]
array_new=np.array(list_new)
print(array_new)
array_new.dtype
#array_new.shape

[2.     5.5    3.1415 0.    ]


dtype('float64')

In [11]:
#Create a 2-dimensional array of integers
list_new2=[[2, 5.5, 3.1415, 0],[3,4,6,7.6]]
array_new2=np.array(list_new2,dtype=int)
print(array_new2)
array_new2.shape

[[2 5 3 0]
 [3 4 6 7]]


(2, 4)

### Creating NumPy array using arange(), linspace() and random() functions

The function `arange()` returns arrays with regularly incrementing values.

In [12]:
# This will create an array of integers from 0 to 9

np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
# An array of floating point numbers, from 2.0 to 9.0 (10 is excluded), with increment of 1.0

np.arange(2, 10, dtype=float)

array([2., 3., 4., 5., 6., 7., 8., 9.])

In [14]:
# An array of numbers from 0 to 10 (exclusive) with 0.6 increment

np.arange(0, 10, 0.6)     # start, end (exclusive), step

array([0. , 0.6, 1.2, 1.8, 2.4, 3. , 3.6, 4.2, 4.8, 5.4, 6. , 6.6, 7.2,
       7.8, 8.4, 9. , 9.6])

When the `arange()` function is used with floating point arguments, it is difficult to estimate the number of elements in the resulting array. If you need to create an array with a predefined number of elements between a start and an end point, use the function `linspace()`. The `linspace()` function receives as an argument the number of elements that we want instead of the step: `linspace(start, stop, number of elements)`.

In [15]:
np.linspace(0.4, 1.1, 7)    # create an array of 7 elements from 0.4 to 1.1 (inclusive)

array([0.4       , 0.51666667, 0.63333333, 0.75      , 0.86666667,
       0.98333333, 1.1       ])

In [16]:
# If the end point should not be included, use endpoint=False parameter

np.linspace(0.4, 1.1, 7, endpoint = False)

array([0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

To generate an array with some random data, we can use `np.random.randn()` function. The sequence of numbers created using this function will be normally distributed around its mean. 

In [17]:
np.random.randn(3)  # 1-dimensional array of 3 normally distributed numbers

array([ 1.1536205 ,  0.03219123, -1.06668911])

In [18]:
#creating 2x3 2-dimensional array of random numbers:

np.random.randn(2, 3)

array([[ 0.98483364,  0.06589472,  0.04142363],
       [-0.24164268, -0.39142735,  2.64031563]])

**`Exercise: Create two arrays of 5 numbers from 5 to 25 using arange() and linspace() functions`**

In [19]:
# type your code here (`arange`)
array1 = np.arange(5,26,5)
print(array1)

# type your code here (`linspace`)
array2 = np.linspace(5,25,5,dtype = int)
print(array2)

[ 5 10 15 20 25]
[ 5 10 15 20 25]
